import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import "@/src/styles/globals.css";
import { Provider } from "jotai";
import AuthProvider from "@/src/components/AuthProvider";
import { Toaster } from "@/src/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flipit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Flipit</title>
      </Head>
      <body className={inter.className}>
        <Provider>
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
